package storage

// StandardSObjects contains definitions for common Salesforce standard objects
var StandardSObjects = []SObjectDefinition{
	{
		Name:        "Account",
		Label:       "Account",
		LabelPlural: "Accounts",
		KeyPrefix:   "001",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Account ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "Name", Label: "Account Name", Type: FieldTypeString, Length: 255, Nillable: false, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "Industry", Label: "Industry", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Agriculture", Label: "Agriculture", Active: true},
					{Value: "Banking", Label: "Banking", Active: true},
					{Value: "Consulting", Label: "Consulting", Active: true},
					{Value: "Education", Label: "Education", Active: true},
					{Value: "Healthcare", Label: "Healthcare", Active: true},
					{Value: "Manufacturing", Label: "Manufacturing", Active: true},
					{Value: "Technology", Label: "Technology", Active: true},
				},
			},
			{Name: "Website", Label: "Website", Type: FieldTypeURL, Nillable: true, Createable: true, Updateable: true},
			{Name: "Phone", Label: "Phone", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "Fax", Label: "Fax", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "Type", Label: "Account Type", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Prospect", Label: "Prospect", Active: true},
					{Value: "Customer - Direct", Label: "Customer - Direct", Active: true},
					{Value: "Customer - Channel", Label: "Customer - Channel", Active: true},
					{Value: "Channel Partner / Reseller", Label: "Channel Partner / Reseller", Active: true},
					{Value: "Installation Partner", Label: "Installation Partner", Active: true},
					{Value: "Technology Partner", Label: "Technology Partner", Active: true},
					{Value: "Other", Label: "Other", Active: true},
				},
			},
			{Name: "BillingStreet", Label: "Billing Street", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "BillingCity", Label: "Billing City", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "BillingState", Label: "Billing State/Province", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "BillingPostalCode", Label: "Billing Zip/Postal Code", Type: FieldTypeString, Length: 20, Nillable: true, Createable: true, Updateable: true},
			{Name: "BillingCountry", Label: "Billing Country", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "ShippingStreet", Label: "Shipping Street", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "ShippingCity", Label: "Shipping City", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "ShippingState", Label: "Shipping State/Province", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "ShippingPostalCode", Label: "Shipping Zip/Postal Code", Type: FieldTypeString, Length: 20, Nillable: true, Createable: true, Updateable: true},
			{Name: "ShippingCountry", Label: "Shipping Country", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "AnnualRevenue", Label: "Annual Revenue", Type: FieldTypeCurrency, Nillable: true, Createable: true, Updateable: true},
			{Name: "NumberOfEmployees", Label: "Employees", Type: FieldTypeInteger, Nillable: true, Createable: true, Updateable: true},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "ParentId", Label: "Parent Account ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account"}, RelationshipName: "Parent"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
		ChildRelationships: []ChildRelationship{
			{ChildSObject: "Contact", Field: "AccountId", RelationshipName: "Contacts", CascadeDelete: false},
			{ChildSObject: "Opportunity", Field: "AccountId", RelationshipName: "Opportunities", CascadeDelete: false},
			{ChildSObject: "Case", Field: "AccountId", RelationshipName: "Cases", CascadeDelete: false},
		},
	},
	{
		Name:        "Contact",
		Label:       "Contact",
		LabelPlural: "Contacts",
		KeyPrefix:   "003",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Contact ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "FirstName", Label: "First Name", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "LastName", Label: "Last Name", Type: FieldTypeString, Length: 80, Nillable: false, Createable: true, Updateable: true},
			{Name: "Name", Label: "Full Name", Type: FieldTypeString, Length: 121, Nillable: false, Createable: false, Updateable: false},
			{Name: "Email", Label: "Email", Type: FieldTypeEmail, Nillable: true, Createable: true, Updateable: true},
			{Name: "Phone", Label: "Phone", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "MobilePhone", Label: "Mobile", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "HomePhone", Label: "Home Phone", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "AccountId", Label: "Account ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account"}, RelationshipName: "Account"},
			{Name: "Title", Label: "Title", Type: FieldTypeString, Length: 128, Nillable: true, Createable: true, Updateable: true},
			{Name: "Department", Label: "Department", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "Birthdate", Label: "Birthdate", Type: FieldTypeDate, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "MailingStreet", Label: "Mailing Street", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "MailingCity", Label: "Mailing City", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "MailingState", Label: "Mailing State/Province", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "MailingPostalCode", Label: "Mailing Zip/Postal Code", Type: FieldTypeString, Length: 20, Nillable: true, Createable: true, Updateable: true},
			{Name: "MailingCountry", Label: "Mailing Country", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "Lead",
		Label:       "Lead",
		LabelPlural: "Leads",
		KeyPrefix:   "00Q",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Lead ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "FirstName", Label: "First Name", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "LastName", Label: "Last Name", Type: FieldTypeString, Length: 80, Nillable: false, Createable: true, Updateable: true},
			{Name: "Name", Label: "Full Name", Type: FieldTypeString, Length: 121, Nillable: false, Createable: false, Updateable: false},
			{Name: "Company", Label: "Company", Type: FieldTypeString, Length: 255, Nillable: false, Createable: true, Updateable: true},
			{Name: "Email", Label: "Email", Type: FieldTypeEmail, Nillable: true, Createable: true, Updateable: true},
			{Name: "Phone", Label: "Phone", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "Status", Label: "Status", Type: FieldTypePicklist, Nillable: false, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Open - Not Contacted", Label: "Open - Not Contacted", Active: true, DefaultValue: true},
					{Value: "Working - Contacted", Label: "Working - Contacted", Active: true},
					{Value: "Closed - Converted", Label: "Closed - Converted", Active: true},
					{Value: "Closed - Not Converted", Label: "Closed - Not Converted", Active: true},
				},
			},
			{Name: "Industry", Label: "Industry", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true},
			{Name: "Title", Label: "Title", Type: FieldTypeString, Length: 128, Nillable: true, Createable: true, Updateable: true},
			{Name: "Website", Label: "Website", Type: FieldTypeURL, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "Street", Label: "Street", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "City", Label: "City", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "State", Label: "State/Province", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "PostalCode", Label: "Zip/Postal Code", Type: FieldTypeString, Length: 20, Nillable: true, Createable: true, Updateable: true},
			{Name: "Country", Label: "Country", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "LeadSource", Label: "Lead Source", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "IsConverted", Label: "Converted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
			{Name: "ConvertedAccountId", Label: "Converted Account ID", Type: FieldTypeReference, Nillable: true, Createable: false, Updateable: false, ReferenceTo: []string{"Account"}},
			{Name: "ConvertedContactId", Label: "Converted Contact ID", Type: FieldTypeReference, Nillable: true, Createable: false, Updateable: false, ReferenceTo: []string{"Contact"}},
			{Name: "ConvertedOpportunityId", Label: "Converted Opportunity ID", Type: FieldTypeReference, Nillable: true, Createable: false, Updateable: false, ReferenceTo: []string{"Opportunity"}},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "Opportunity",
		Label:       "Opportunity",
		LabelPlural: "Opportunities",
		KeyPrefix:   "006",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Opportunity ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "Name", Label: "Opportunity Name", Type: FieldTypeString, Length: 120, Nillable: false, Createable: true, Updateable: true},
			{Name: "AccountId", Label: "Account ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account"}, RelationshipName: "Account"},
			{Name: "Amount", Label: "Amount", Type: FieldTypeCurrency, Nillable: true, Createable: true, Updateable: true},
			{Name: "CloseDate", Label: "Close Date", Type: FieldTypeDate, Nillable: false, Createable: true, Updateable: true},
			{Name: "StageName", Label: "Stage", Type: FieldTypePicklist, Nillable: false, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Prospecting", Label: "Prospecting", Active: true},
					{Value: "Qualification", Label: "Qualification", Active: true},
					{Value: "Needs Analysis", Label: "Needs Analysis", Active: true},
					{Value: "Value Proposition", Label: "Value Proposition", Active: true},
					{Value: "Id. Decision Makers", Label: "Id. Decision Makers", Active: true},
					{Value: "Perception Analysis", Label: "Perception Analysis", Active: true},
					{Value: "Proposal/Price Quote", Label: "Proposal/Price Quote", Active: true},
					{Value: "Negotiation/Review", Label: "Negotiation/Review", Active: true},
					{Value: "Closed Won", Label: "Closed Won", Active: true},
					{Value: "Closed Lost", Label: "Closed Lost", Active: true},
				},
			},
			{Name: "Probability", Label: "Probability (%)", Type: FieldTypePercent, Nillable: true, Createable: true, Updateable: true},
			{Name: "Type", Label: "Opportunity Type", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Existing Customer - Upgrade", Label: "Existing Customer - Upgrade", Active: true},
					{Value: "Existing Customer - Replacement", Label: "Existing Customer - Replacement", Active: true},
					{Value: "Existing Customer - Downgrade", Label: "Existing Customer - Downgrade", Active: true},
					{Value: "New Customer", Label: "New Customer", Active: true},
				},
			},
			{Name: "LeadSource", Label: "Lead Source", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true},
			{Name: "NextStep", Label: "Next Step", Type: FieldTypeString, Length: 255, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "IsClosed", Label: "Closed", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsWon", Label: "Won", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "Case",
		Label:       "Case",
		LabelPlural: "Cases",
		KeyPrefix:   "500",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Case ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "CaseNumber", Label: "Case Number", Type: FieldTypeString, Length: 30, Nillable: false, Createable: false, Updateable: false},
			{Name: "Subject", Label: "Subject", Type: FieldTypeString, Length: 255, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "Status", Label: "Status", Type: FieldTypePicklist, Nillable: false, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "New", Label: "New", Active: true, DefaultValue: true},
					{Value: "Working", Label: "Working", Active: true},
					{Value: "Escalated", Label: "Escalated", Active: true},
					{Value: "Closed", Label: "Closed", Active: true},
				},
			},
			{Name: "Priority", Label: "Priority", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "High", Label: "High", Active: true},
					{Value: "Medium", Label: "Medium", Active: true, DefaultValue: true},
					{Value: "Low", Label: "Low", Active: true},
				},
			},
			{Name: "Origin", Label: "Case Origin", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Phone", Label: "Phone", Active: true},
					{Value: "Email", Label: "Email", Active: true},
					{Value: "Web", Label: "Web", Active: true},
				},
			},
			{Name: "Type", Label: "Type", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true},
			{Name: "Reason", Label: "Case Reason", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true},
			{Name: "AccountId", Label: "Account ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account"}, RelationshipName: "Account"},
			{Name: "ContactId", Label: "Contact ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Contact"}, RelationshipName: "Contact"},
			{Name: "IsClosed", Label: "Closed", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsEscalated", Label: "Escalated", Type: FieldTypeBoolean, Nillable: false, Createable: true, Updateable: true},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "User",
		Label:       "User",
		LabelPlural: "Users",
		KeyPrefix:   "005",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   false,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "User ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "Username", Label: "Username", Type: FieldTypeString, Length: 80, Nillable: false, Createable: true, Updateable: true, Unique: true},
			{Name: "FirstName", Label: "First Name", Type: FieldTypeString, Length: 40, Nillable: true, Createable: true, Updateable: true},
			{Name: "LastName", Label: "Last Name", Type: FieldTypeString, Length: 80, Nillable: false, Createable: true, Updateable: true},
			{Name: "Name", Label: "Full Name", Type: FieldTypeString, Length: 121, Nillable: false, Createable: false, Updateable: false},
			{Name: "Email", Label: "Email", Type: FieldTypeEmail, Nillable: false, Createable: true, Updateable: true},
			{Name: "Alias", Label: "Alias", Type: FieldTypeString, Length: 8, Nillable: false, Createable: true, Updateable: true},
			{Name: "IsActive", Label: "Active", Type: FieldTypeBoolean, Nillable: false, Createable: true, Updateable: true},
			{Name: "ProfileId", Label: "Profile ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"Profile"}},
			{Name: "UserRoleId", Label: "Role ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"UserRole"}},
			{Name: "Title", Label: "Title", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "Department", Label: "Department", Type: FieldTypeString, Length: 80, Nillable: true, Createable: true, Updateable: true},
			{Name: "Phone", Label: "Phone", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "MobilePhone", Label: "Mobile", Type: FieldTypePhone, Nillable: true, Createable: true, Updateable: true},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "Task",
		Label:       "Task",
		LabelPlural: "Tasks",
		KeyPrefix:   "00T",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Task ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "Subject", Label: "Subject", Type: FieldTypeString, Length: 255, Nillable: true, Createable: true, Updateable: true},
			{Name: "Status", Label: "Status", Type: FieldTypePicklist, Nillable: false, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "Not Started", Label: "Not Started", Active: true, DefaultValue: true},
					{Value: "In Progress", Label: "In Progress", Active: true},
					{Value: "Completed", Label: "Completed", Active: true},
					{Value: "Waiting on someone else", Label: "Waiting on someone else", Active: true},
					{Value: "Deferred", Label: "Deferred", Active: true},
				},
			},
			{Name: "Priority", Label: "Priority", Type: FieldTypePicklist, Nillable: true, Createable: true, Updateable: true,
				PicklistValues: []PicklistValue{
					{Value: "High", Label: "High", Active: true},
					{Value: "Normal", Label: "Normal", Active: true, DefaultValue: true},
					{Value: "Low", Label: "Low", Active: true},
				},
			},
			{Name: "WhoId", Label: "Name ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Contact", "Lead"}},
			{Name: "WhatId", Label: "Related To ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account", "Opportunity", "Case"}},
			{Name: "ActivityDate", Label: "Due Date Only", Type: FieldTypeDate, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "IsClosed", Label: "Closed", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
	{
		Name:        "Event",
		Label:       "Event",
		LabelPlural: "Events",
		KeyPrefix:   "00U",
		Custom:      false,
		Createable:  true,
		Updateable:  true,
		Deletable:   true,
		Queryable:   true,
		Fields: []FieldDefinition{
			{Name: "Id", Label: "Event ID", Type: FieldTypeID, Nillable: false, Createable: false, Updateable: false},
			{Name: "Subject", Label: "Subject", Type: FieldTypeString, Length: 255, Nillable: true, Createable: true, Updateable: true},
			{Name: "StartDateTime", Label: "Start Date Time", Type: FieldTypeDatetime, Nillable: true, Createable: true, Updateable: true},
			{Name: "EndDateTime", Label: "End Date Time", Type: FieldTypeDatetime, Nillable: true, Createable: true, Updateable: true},
			{Name: "IsAllDayEvent", Label: "All-Day Event", Type: FieldTypeBoolean, Nillable: false, Createable: true, Updateable: true},
			{Name: "WhoId", Label: "Name ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Contact", "Lead"}},
			{Name: "WhatId", Label: "Related To ID", Type: FieldTypeReference, Nillable: true, Createable: true, Updateable: true, ReferenceTo: []string{"Account", "Opportunity", "Case"}},
			{Name: "Location", Label: "Location", Type: FieldTypeString, Length: 255, Nillable: true, Createable: true, Updateable: true},
			{Name: "Description", Label: "Description", Type: FieldTypeTextArea, Nillable: true, Createable: true, Updateable: true},
			{Name: "OwnerId", Label: "Owner ID", Type: FieldTypeReference, Nillable: false, Createable: true, Updateable: true, ReferenceTo: []string{"User"}, RelationshipName: "Owner"},
			{Name: "CreatedDate", Label: "Created Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "CreatedById", Label: "Created By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "LastModifiedDate", Label: "Last Modified Date", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "LastModifiedById", Label: "Last Modified By ID", Type: FieldTypeReference, Nillable: false, Createable: false, Updateable: false, ReferenceTo: []string{"User"}},
			{Name: "SystemModstamp", Label: "System Modstamp", Type: FieldTypeDatetime, Nillable: false, Createable: false, Updateable: false},
			{Name: "IsDeleted", Label: "Deleted", Type: FieldTypeBoolean, Nillable: false, Createable: false, Updateable: false},
		},
	},
}
